theme: jekyll-theme-minimal
title: Wadsworth | APC Bot Assistant
description: Wadsworth is a multi-modular application designed to streamline repetitive processes into a single discord command interface
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
